language: perl
dist: bionic
env:
  global:
    - HARNESS_OPTIONS=j9
    - TEST_EV=1
    - TEST_POD=1
    - TEST_SOCKS=1
    - TEST_SUBPROCESS=1
    - TEST_UNIX=1
    - TEST_TLS=1
sudo: false
notifications:
  email: false
