language: perl
dist: bionic
env:
  global:
    - HARNESS_OPTIONS=j9
    - TEST_EV=1
    - TEST_POD=1
    - TEST_SOCKS=1
    - TEST_SUBPROCESS=1
    - TEST_UNIX=1
    - TEST_TLS=1
install:
  - cpanm -n Cpanel::JSON::XS EV~"!= 4.28" IO::Socket::Socks IO::Socket::SSL
  - cpanm -n Net::DNS::Native Role::Tiny Test::Pod Test::Pod::Coverage
  - cpanm -n --installdeps .
sudo: false
notifications:
  email: false
